"""On-MCU raster lookup: GPS latitude/longitude to a timezone index.

Walks the RLE-encoded global grid frozen in :mod:`tz_offset._tzdata` (generated by
the host-only ``tzgen`` tool) to find the timezone index covering a point. Pure
integer math after one float-to-micro-degree conversion, no I/O — so it runs
identically on the MCU and under host CPython pytest.

Grid convention (must match ``tzgen.rasterize``): row 0 is the southernmost
latitude band, col 0 the westernmost longitude band, row-major; each cell spans
``R_UDEG`` micro-degrees. The reserved value ``OCEAN`` marks cells no zone covers,
for which the caller falls back to a longitude-derived offset.
"""

from tz_offset import _tzdata

_LAT_ORIGIN_UDEG = 90_000_000
_LON_ORIGIN_UDEG = 180_000_000


def tz_index_for(lat: float, lon: float) -> int:
    """Return the timezone index covering ``(lat, lon)``, or ``None`` if uncovered.

    Args:
        lat: Latitude in decimal degrees (north positive).
        lon: Longitude in decimal degrees (east positive); wrapped across the
            date line.

    Returns:
        The integer index into ``_tzdata.POSIX``/``_tzdata.TZIDS`` for the covering
        zone, or ``None`` for ocean / out-of-coverage cells.
    """
    lon = ((lon + 180.0) % 360.0) - 180.0
    row = (round(lat * 1_000_000) + _LAT_ORIGIN_UDEG) // _tzdata.R_UDEG
    col = (round(lon * 1_000_000) + _LON_ORIGIN_UDEG) // _tzdata.R_UDEG
    if row < 0:
        row = 0
    elif row >= _tzdata.ROWS:
        row = _tzdata.ROWS - 1
    if col < 0:
        col = 0
    elif col >= _tzdata.COLS:
        col = _tzdata.COLS - 1
    target = row * _tzdata.COLS + col

    grid = _tzdata.GRID
    total = len(grid)
    pos = 0
    cumulative = 0
    while pos < total:
        cumulative += (grid[pos] << 8) | grid[pos + 1]
        if target < cumulative:
            value = (grid[pos + 2] << 8) | grid[pos + 3]
            return None if value == _tzdata.OCEAN else value
        pos += 4
    return None
