---
services:
  wheels:
    build:
      context: ../..
      dockerfile: Dockerfile.host
      target: wheels
    command: ["true"]

  pi-compile:
    build:
      context: ../..
      dockerfile: Dockerfile.firmware
      target: pi-compile
    volumes:
      - ../../firmware-packages:/firmware-packages:ro
      - ./firmware:/firmware:ro
      - ./outputs:/outputs
  viz:
    build:
      context: ../..
      dockerfile: Dockerfile.host
      target: viz
      additional_contexts:
        wheels: service:wheels
      args:
        VIZ_DIR: projects/ld2450/viz
    volumes:
      - /dev:/dev
    device_cgroup_rules:
      - c 166:* rmw
    ports:
      - 18501:18501
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - SERIAL_PORT=${SERIAL_PORT:-/dev/ttyACM0}
