---
services:
  pi-compile:
    build:
      context: ../..
      dockerfile: Dockerfile.firmware
      target: rp
    volumes:
      - ../../firmware-packages:/firmware-packages:ro
      - ./firmware:/firmware:ro
      - ./outputs:/outputs
      - build-cache:/build-cache
      - ../../pyproject.toml:/root_pyproject.toml:ro
      - ./pyproject.toml:/project_pyproject.toml:ro
      - ../../.githooks/check_project_compat.sh:/check_project_compat.sh:ro

  esp32-compile:
    build:
      context: ../..
      dockerfile: Dockerfile.firmware
      target: esp32-compile
    volumes:
      - ../../firmware-packages:/firmware-packages:ro
      - ./firmware:/firmware:ro
      - ./outputs:/outputs
      - ../../pyproject.toml:/root_pyproject.toml:ro
      - ./pyproject.toml:/project_pyproject.toml:ro
      - ../../.githooks/check_project_compat.sh:/check_project_compat.sh:ro

  esp32-flash:
    build:
      context: ../..
      dockerfile: Dockerfile.firmware
      target: esp32-flash
    depends_on:
      esp32-compile:
        condition: service_completed_successfully
    volumes:
      - ../../firmware-packages:/firmware-packages:ro
      - ./firmware:/firmware:ro
      - ./outputs:/outputs
      - /dev:/dev
      - ../../pyproject.toml:/root_pyproject.toml:ro
      - ./pyproject.toml:/project_pyproject.toml:ro
      - ../../.githooks/check_project_compat.sh:/check_project_compat.sh:ro
    device_cgroup_rules:
      - c 166:* rmw  # USB-ACM (TTY) major

  viz:
    build:
      context: ../..
      dockerfile: Dockerfile.host
      target: viz
      args:
        VIZ_DIR: projects/distance-stream/viz
    volumes:
      - /dev:/dev
    device_cgroup_rules:
      - c 166:* rmw  # USB-ACM (TTY) major
    ports:
      - 18501:18501
    environment:
      - SERIAL_PORT=/dev/ttyACM0
volumes:
  build-cache:
